<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ $title ?? config('app.name', 'Student Portal') }}</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

    <!-- Styles & Scripts -->
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    @livewireStyles

    {{-- ✅ reCAPTCHA script (auto-generated by package) --}}
    {!! NoCaptcha::renderJs() !!}
</head>
<body class="antialiased font-sans text-gray-900 bg-gray-100">

    <div class="min-h-screen flex flex-col items-center justify-center py-6 px-4 sm:px-6 lg:px-8">
        {{-- ✅ Slot or @yield --}}
        @isset($slot)
            {{ $slot }}
        @else
            @yield('content')
        @endisset
    </div>

    @livewireScripts
</body>
</html>
